/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "Stm32F103xx.h"
#include "RCC_interface.h"
#include "GPIO_interface.h"


const char x  = 20; /*stored in rodata section, check map file */

void main(void)
{

	/* enable clock to GPIOA*/

	/* Configure Pin A5 as: output, pushpull, No Pull, Lowspeed */



	/* Loop forever */
	for(;;);
}
