/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

//#define SRAM_START (0x20000000U)
//#define SRAM_SIZE (128 * 1024)
//#define SRAM_END (SRAM_START + SRAM_SIZE)
//#define STACK_START (SRAM_END)
//
//#define STACK_MSP_START  (SRAM_END - 1024)
//#define  STACK_MSP_END   (STACK_MSP_START + 512)
//#define STACK_PSP_START  (STACK_MSP_END)
//#define STACK_PSP_END    (SRAM_END)


int Add(int A, int B, int C, int D);
void GenerateException(void);

int main(void)
{
//	__asm volatile("LDR R0, =#STACK_PSP_END"); // caused error

	uint32_t SPVal = 0x02; // 0b00000010 SEL PSP Pin
	__asm volatile(".equ SRAM_END, (0x20000000 + (4 * 1024))");
	__asm volatile(".equ STACK_PSP_END, SRAM_END - 512");

	/* Initialize PSP with valid stack pointer value */
	__asm volatile("LDR R0, =STACK_PSP_END");
	__asm volatile("MSR PSP, R0");

	/*2- Link SP to PSP */
	__asm volatile("MSR CONTROL, %0"::"r"(SPVal));


    /* Loop forever */

	int Result ;
	Result = Add(1, 2 , 3 , 4);

	GenerateException();

	for(;;);
}


int Add(int A, int B, int C, int D)
{
	return A + B + C + D;
}
void GenerateException(void)
{
	__asm volatile ("SVC #0x2");
}

void SVC_Handler(void)
{
	//
	int Result ;
	Result = Add(1, 2 , 3 , 4);
}
