/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "Stm32F446xx.h"
#include "RCC_interface.h"
#include "GPIO_interface.h"


const char x  = 20; /*stored in rodata section, check map file */

int main(void)
{

	/* enable clock to GPIOA*/
	RCC_voidAHB1EnablePeripheralClock(0); /* GPIOA */

	/* Configure Pin A5 as: output, pushpull, No Pull, Lowspeed */

	GPIO_PinConfig_t LedPin =
	{
			.Port = PORTA,
			.PinNum = PIN5,
			.Mode = OUTPUT,
			.OutPutType = PUSH_PULL,
			.Speed = LOW,
			.PullType = NOPULL
	};

	GPIO_u8PinInit(&LedPin);

	GPIO_u8SetPinValue(PORTA, PIN5, PIN_HIGH);

	/* Loop forever */
	for(;;);
}
