#ifndef RCC_PRIVATE_H_
#define RCC_PRIVATE_H_


#define RCC_BASE_ADDRESS 0x40021000

#define NOT_RDY   0U

#define RCC_CFGR_SYSLCK_SW_HSI_MASK 0b00
#define RCC_CFGR_SYSLCK_SW_HSE_MASK 0b01
#define RCC_CFGR_SYSLCK_SW_PLL_MASK 0b11

#define RCC_CFGR_PLLMUL_MASK 0xFFC3FFFF


#endif /* RCC_PRIVATE_H_ */
