/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>


int main(void)
{
	uint32_t CTRL_Reg = 20;
	__asm volatile ("MRS  %0 ,CONTROL":"=r"(CTRL_Reg));  // put 0X20001000 value inside R1
	/*
	int VAR = 10;
	__asm volatile ("MOV R0, %0"::"r"(VAR));  // put 0X20001000 value inside R1
	 */

	/*
	__asm volatile ("LDR R1, =#0x20001000");  // put 0X20001000 value inside R1

	__asm volatile ("LDR R2, =#0x20001004");  // put 0X20001004 value inside R2

	__asm volatile ("LDR R0, [R1]"); // get address inside R1, fetch the data, put it inside R0

	__asm volatile ("LDR R1, [R2]"); // get address inside R2, fetch the data, put it inside R1

	__asm volatile ("ADD R0, R0, R1"); // Add operands in R0, R1, put result inside R0

	__asm volatile ("STR R0, [R2]"); // Store value from R0 inside memory location whose address is R2
	*/

	/* Loop forever */
	for(;;);
}
